repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint-backend
        name: lint-backend
        language: system
        entry: bash -c 'ROOTDIR=$(git rev-parse --show-toplevel) && cd $ROOTDIR/backend && make lint'
        pass_filenames: false
        types: [go]
        files: ^backend/
