# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    container_name: harbour_db
    image: postgres:15.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    container_name: harbour_migrate
    depends_on:
      - db
    image: arigaio/atlas:0.9.0
    volumes:
      - "./database:/tmp/database"
    command: >
      schema apply \
        --auto-approve \
        --url "postgres://test:test@harbour_db:5432/test?sslmode=disable" \
        --to "file://tmp/database/schema.hcl" \
        --dev-url "postgres://test:test@harbour_db:5432/test?sslmode=disable"

  pgadmin:
    container_name: harbour_admin
    depends_on:
      - db
    image: dpage/pgadmin4
    #user: root
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "8080:80"
    volumes:
      - .data/pgadmin:/var/lib/pgadmin
      